from __future__ import annotations

import csv
import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
LEVY_DIR = ROOT / "analysis" / "levy_paper"
FIGURES_DIR = LEVY_DIR / "figures"
FINAL_DIR = FIGURES_DIR / "main_figures"
SUPPLEMENTARY_DIR = FIGURES_DIR / "supplementary_figures"
SOURCE_DATA_DIR = FIGURES_DIR / "source_data"
POLISHED_DIR = LEVY_DIR / "outputs" / "final" / "fig4_fig5_polished"
FIGURE1_DIR = LEVY_DIR / "outputs" / "final" / "figure1_transport_mechanism"
FIGURE2_DIR = LEVY_DIR / "outputs" / "final" / "figure2_transport_phenotype"

FIGURE_MANIFEST_PATH = FIGURES_DIR / "figure_manifest.csv"
FINAL_MANIFEST_PATH = FINAL_DIR / "final_figure_manifest.csv"
SOURCE_DATA_MANIFEST_PATH = SOURCE_DATA_DIR / "source_data_manifest.csv"
README_PATH = FIGURES_DIR / "README.md"


def _rel(path: Path) -> str:
    return str(path.relative_to(ROOT)).replace("\\", "/")


def _copy_if_available(source: Path, destination: Path) -> str:
    if not source.exists():
        return "missing_source"
    destination.parent.mkdir(parents=True, exist_ok=True)
    if source.resolve(strict=False) != destination.resolve(strict=False):
        try:
            shutil.copy2(source, destination)
        except OSError as exc:
            if destination.exists():
                return f"kept_existing_{exc.__class__.__name__}"
            raise
    return "copied"


@dataclass(frozen=True)
class FigureAsset:
    figure_id: str
    role: str
    description_short: str
    source_stem: Path
    destination_dir: Path
    source_notebook: Path | None = None
    source_script: Path | None = None
    notes_code_only: str = ""

    @property
    def source_png(self) -> Path:
        return self.source_stem.with_suffix(".png")

    @property
    def source_pdf(self) -> Path:
        return self.source_stem.with_suffix(".pdf")

    @property
    def destination_png(self) -> Path:
        return self.destination_dir / f"{self.figure_id}.png"

    @property
    def destination_pdf(self) -> Path:
        return self.destination_dir / f"{self.figure_id}.pdf"


MAIN_FIGURES = [
    FigureAsset(
        figure_id="figure1_transport_mechanism_schematic",
        role="main",
        description_short="real-match schematic of trajectories, run segmentation, and polarisation",
        source_stem=FIGURE1_DIR / "real_match_transport_mechanism_4panel",
        destination_dir=FINAL_DIR,
        source_notebook=LEVY_DIR / "notebooks_publication" / "01_figure1_transport_mechanism.ipynb",
        source_script=LEVY_DIR / "scripts" / "create_real_match_transport_mechanism_4panel.py",
    ),
    FigureAsset(
        figure_id="figure2_transport_phenotype",
        role="main",
        description_short="transport phenotype and MSD scaling",
        source_stem=FIGURE2_DIR / "main" / "figure2_transport_phenotype_v2",
        destination_dir=FINAL_DIR,
        source_notebook=LEVY_DIR / "notebooks_publication" / "02_figure2_transport_phenotype.ipynb",
        source_script=LEVY_DIR / "scripts" / "create_final_figure2_transport_phenotype.py",
    ),
    FigureAsset(
        figure_id="figure3_order_transport",
        role="main",
        description_short="order-stratified duration and length survival with order-speed phenotype",
        source_stem=LEVY_DIR
        / "outputs"
        / "final"
        / "figure3_order_transport"
        / "figure3_three_panel_candidate_house_style_cluster_bootstrap",
        destination_dir=FINAL_DIR,
        source_notebook=LEVY_DIR / "notebooks_publication" / "03_figure3_order_transport.ipynb",
        source_script=LEVY_DIR / "scripts" / "create_final_figure3_order_transport.py",
        notes_code_only="generated by final Figure 3 script",
    ),
    FigureAsset(
        figure_id="figure4_killed_transport",
        role="main",
        description_short="age-structured killed transport with order-state and tempered survival",
        source_stem=POLISHED_DIR / "figure4_final_polished",
        destination_dir=FINAL_DIR,
        source_notebook=LEVY_DIR / "notebooks_publication" / "04_figure4_killed_transport.ipynb",
        source_script=LEVY_DIR / "scripts" / "create_final_fig4_fig5_polished.py",
        notes_code_only="latest polished Figure 4 output",
    ),
    FigureAsset(
        figure_id="figure5_state_structured_survival",
        role="main",
        description_short="state-structured switching validation and cross-fitted survival diagnostics",
        source_stem=POLISHED_DIR / "figure5_final_polished",
        destination_dir=FINAL_DIR,
        source_notebook=LEVY_DIR / "notebooks_publication" / "05_figure5_state_structured_survival.ipynb",
        source_script=LEVY_DIR / "scripts" / "create_final_fig4_fig5_polished.py",
        notes_code_only="latest polished Figure 5 output",
    ),
]


SUPPLEMENTARY_FIGURES = [
    FigureAsset(
        figure_id="figure4_tail_boundary_diagnostics",
        role="supplementary",
        description_short="tail and boundary diagnostic",
        source_stem=SUPPLEMENTARY_DIR / "figure4_tail_boundary_diagnostics",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="figure5A_selected_transitions",
        role="supplementary",
        description_short="selected transition-rate panel used during Figure 5 design",
        source_stem=SUPPLEMENTARY_DIR / "figure5A_selected_transitions",
        destination_dir=SUPPLEMENTARY_DIR,
        notes_code_only="single-panel Figure 5A diagnostic retained outside final main folder",
    ),
    FigureAsset(
        figure_id="supplementary_crossfitted_generative_survival",
        role="supplementary",
        description_short="cross-fitted generative survival diagnostic",
        source_stem=POLISHED_DIR / "supplementary_crossfitted_generative_survival",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_fixture_survival_error",
        role="supplementary",
        description_short="fixture-level survival error diagnostic",
        source_stem=POLISHED_DIR / "supplementary_fixture_survival_error",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_full_transition_matrices",
        role="supplementary",
        description_short="full transition matrices",
        source_stem=POLISHED_DIR / "supplementary_full_transition_matrices",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_late_early_transition_contrast",
        role="supplementary",
        description_short="late versus early transition contrast",
        source_stem=POLISHED_DIR / "supplementary_late_early_transition_contrast",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_all_state_composition",
        role="supplementary",
        description_short="all-state survivor composition",
        source_stem=POLISHED_DIR / "supplementary_all_state_composition",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_all_state_exposure",
        role="supplementary",
        description_short="all-state exposure diagnostic",
        source_stem=POLISHED_DIR / "supplementary_all_state_exposure",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_season_transfer",
        role="supplementary",
        description_short="season-transfer stress test",
        source_stem=POLISHED_DIR / "supplementary_season_transfer",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_crossfitted_interval_hazard_calibration",
        role="supplementary",
        description_short="cross-fitted interval hazard calibration",
        source_stem=POLISHED_DIR / "supplementary_crossfitted_interval_hazard_calibration",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_crossfitted_state_conditioned_hazard_calibration",
        role="supplementary",
        description_short="cross-fitted state-conditioned hazard calibration",
        source_stem=POLISHED_DIR / "supplementary_crossfitted_state_conditioned_hazard_calibration",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_s0_s1_s2_composition_robustness",
        role="supplementary",
        description_short="state-composition robustness for S0/S1/S2",
        source_stem=POLISHED_DIR / "supplementary_s0_s1_s2_composition_robustness",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
    FigureAsset(
        figure_id="supplementary_team_specific_results",
        role="supplementary",
        description_short="team-specific diagnostic results",
        source_stem=POLISHED_DIR / "supplementary_team_specific_results",
        destination_dir=SUPPLEMENTARY_DIR,
    ),
]


SOURCE_DATA_PATTERNS = ("*.csv", "*.json", "*.md", "*.txt")


def _sync_figure_assets(assets: list[FigureAsset], generated_at: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for asset in assets:
        png_status = _copy_if_available(asset.source_png, asset.destination_png)
        pdf_status = _copy_if_available(asset.source_pdf, asset.destination_pdf)
        if png_status == "copied" and pdf_status == "copied":
            status = "copied"
        elif png_status == "missing_source" and pdf_status == "missing_source":
            status = "missing_source"
        else:
            status = f"partial_png_{png_status}_pdf_{pdf_status}"

        rows.append(
            {
                "figure_id": asset.figure_id,
                "role": asset.role,
                "description_short": asset.description_short,
                "png_path": _rel(asset.destination_png),
                "pdf_path": _rel(asset.destination_pdf),
                "source_png": _rel(asset.source_png),
                "source_pdf": _rel(asset.source_pdf),
                "source_notebook": _rel(asset.source_notebook) if asset.source_notebook else "",
                "source_script": _rel(asset.source_script) if asset.source_script else "",
                "status": status,
                "generated_at": generated_at,
                "notes_code_only": asset.notes_code_only,
            }
        )
    return rows


def _sync_source_data(generated_at: str) -> list[dict[str, str]]:
    SOURCE_DATA_DIR.mkdir(parents=True, exist_ok=True)
    rows: list[dict[str, str]] = []
    seen: set[Path] = set()
    for pattern in SOURCE_DATA_PATTERNS:
        for source in sorted(POLISHED_DIR.glob(pattern)):
            if source in seen or not source.is_file():
                continue
            seen.add(source)
            destination = SOURCE_DATA_DIR / source.name
            status = _copy_if_available(source, destination)
            rows.append(
                {
                    "file_name": source.name,
                    "path": _rel(destination),
                    "source_path": _rel(source),
                    "status": status,
                    "generated_at": generated_at,
                }
            )
    return rows


def _write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        return
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def _write_readme(generated_at: str, figure_rows: list[dict[str, str]]) -> None:
    main_count = sum(
        row["role"] == "main" and not row["status"].startswith("missing_source") for row in figure_rows
    )
    supp_count = sum(
        row["role"] == "supplementary" and not row["status"].startswith("missing_source") for row in figure_rows
    )
    README_PATH.write_text(
        "\n".join(
            [
                "# Levy Paper Figure Exports",
                "",
                "Use these folders for sharing current paper figures:",
                "",
                "- `main_figures/`: manuscript main figures plus retained candidate figures.",
                "- `supplementary_figures/`: supplementary and diagnostic figures.",
                "- `source_data/`: source CSVs, manifests, captions, and audit summaries for the current polished Figure 4/5 exports.",
                "",
                f"Last synced: `{generated_at}`.",
                f"Main manuscript figures copied: `{main_count}`.",
                f"Supplementary figures copied: `{supp_count}`.",
                "",
                "See `figure_manifest.csv` for the source file used for every exported figure.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def sync_final_figures() -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    generated_at = datetime.now().isoformat(timespec="seconds")
    FINAL_DIR.mkdir(parents=True, exist_ok=True)
    SUPPLEMENTARY_DIR.mkdir(parents=True, exist_ok=True)
    SOURCE_DATA_DIR.mkdir(parents=True, exist_ok=True)

    figure_rows = _sync_figure_assets(MAIN_FIGURES + SUPPLEMENTARY_FIGURES, generated_at)
    source_rows = _sync_source_data(generated_at)

    _write_csv(FIGURE_MANIFEST_PATH, figure_rows)
    _write_csv(FINAL_MANIFEST_PATH, [row for row in figure_rows if row["role"] == "main"])
    _write_csv(SOURCE_DATA_MANIFEST_PATH, source_rows)
    _write_readme(generated_at, figure_rows)
    return figure_rows, source_rows


def main() -> None:
    figure_rows, source_rows = sync_final_figures()
    print(f"FIGURES_DIR {FIGURES_DIR}")
    print(f"FINAL_DIR {FINAL_DIR}")
    print(f"SUPPLEMENTARY_DIR {SUPPLEMENTARY_DIR}")
    print(f"SOURCE_DATA_DIR {SOURCE_DATA_DIR}")
    print(f"FIGURE_MANIFEST {FIGURE_MANIFEST_PATH}")
    print(f"SOURCE_DATA_MANIFEST {SOURCE_DATA_MANIFEST_PATH}")
    print(f"README {README_PATH}")
    for row in figure_rows:
        print(f"{row['role']} {row['figure_id']} {row['status']}")
    print(f"source_data_files {len(source_rows)}")


if __name__ == "__main__":
    main()
